config/routes.rb
Rails.application.routes.draw do
  root 'room#index'

  resources :room do
    resources :message
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  after_create { broadcast_message }

  validates_presence_of :data, :data_type

  def broadcast_message
    ActionCable.server.broadcast("chat_room_channel_#{room_id}", self)
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

app/controllers/message_controller.rb
class MessageController < ApplicationController
  def index
    @messages = Message.includes(:room).where(room: { id: params[:room_id] })
    @room_id = params[:room_id]
  end

  def create
    @room = Room.find(params[:room_id])
    @message = @room.messages.create(message_params)

    render json: { errors: @message.errors } if @message.errors.present?
  end

  private
  def message_params
    params.require(:message).permit(:data, :data_type, :file, :room)
  end
end

app/controllers/room_controller.rb
class RoomController < ApplicationController
  def index
    @room = Room.all.order('updated_at')
  end

  def show
    @room = Room.find(params[:id])
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)

    if @room.save
      redirect_to :room_path
    else
      render :new
    end
  end

  private

  def room_params
    params.require(:room).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/room_helper.rb
module RoomHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatBot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/message/index.html.erb
<h1>Lista de mensagens</h1>

<div style="display: flex; flex-direction: column" class="messages-content" id="room-id" data-room-id="<%= @room_id %>">
  <% @messages.each do |message| %>
    <div style="margin: 16px 0">
      <span>-> <%= message.data %></span>
    </div>
  <% end %>
</div>

app/views/room/_form.html.erb
<div>
  <%= form_with model: room do |form| %>
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
      <% room.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/room/index.html.erb
<h1>Lista de salas</h1>

<%= link_to 'Nova sala', new_room_path %>

app/views/room/new.html.erb
<h1> Nova sala </h1>

<%= render "form", room: @room %>